name: Blauhaus Packages
on:
  push:
    branches:
    - release/*

jobs:

  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Set Version
       run: |
        npm install @actions/core --save
        node ./scripts/getversion.js
     - name: Build NuGet Package
       run: |
        dotnet build ./src/Onsight.ApiClient.sln --configuration Release
        dotnet pack ./src/Onsight.ApiClient/Onsight.ApiClient.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
      - name: Variable Substitution appsettings file for tests
        uses: microsoft/variable-substitution@v1
        with:
          files: '.src/Onsight.ApiClient.Tests.Tests/appsettings.json'
          env:
            AppSettings.AppTest3_ApiKey: "${{ secrets.APPTEST3_APIKEY}}"
            AppSettings.AppTest3_ApiSecret: "${{ secrets.APPTEST3_APISECRET }}"
     - name: Run Tests
       run: |
        dotnet test ./src/Onsight.ApiClient.Tests/Onsight.ApiClient.Tests.csproj